#!/bin/bash

echo "Bootstrapping..."
dub build --compiler=dmd || exit $?
dub build --root source/wrap --compiler=dmd || exit $?

cp source/wrap/bb-wrap-bootstrap ./ || exit $?

export PYTHONPATH=tools/python:$PYTHONPATH

echo "Building with the One True Build System..."
rm -f .*bb.json.state || exit $?
./bb-bootstrap build
