#!/bin/bash

# First use DUB to build.
echo "Bootstrapping..."
dub build --compiler=dmd

# Then generate the build description for Brilliant Build to consume.
export PYTHONPATH=tools/python:$PYTHONPATH
./build.py bb.json

# Then have the build system build the build system!
echo "Building with the One True Build System..."
rm -f .bb.json.state
./bb build -f bb.json
