#!/bin/bash

echo "Bootstrapping..."
dub build --compiler=dmd || exit 1
dub build --root source/wrap --compiler=dmd || exit 1

cp source/wrap/bb-wrap-bootstrap ./ || exit 1

export PYTHONPATH=tools/python:$PYTHONPATH

echo "Building with the One True Build System..."
rm -f .*bb.json.state || exit 1
./bb-bootstrap build
