
assert(glob.match("", ""))
assert(glob.match("", "*"))
assert(glob.match("foo", "foo"))
assert(glob.match("foo.c", "*.c"))
assert(glob.match("foo", "foo*"))
assert(glob.match("foo.bar.baz", "*.*.*"))
assert(glob.match("foo.bar.baz", "f*.b*.b*"))
assert(glob.match("foo", "[bf]oo"))
assert(glob.match("zoo", "[!bf]oo"))
assert(glob.match("foo.c", "[fb]*.c"))

assert(not glob.match("", "a"))
assert(not glob.match("a", ""))
assert(not glob.match("foo", "bar"))
assert(not glob.match("foo.bar", "foo"))
assert(not glob.match("foo.d", "*.c"))
assert(not glob.match("foo.bar.baz", "f*.f*.f*"))
assert(not glob.match("zoo", "[bf]oo"))
assert(not glob.match("zoo", "[!bzf]oo"))
